"use strict";
var genders = ["Male", "Female"];
var male_list = "Noah\n" +
    "Liam\n" +
    "Mason\n" +
    "Jacob\n" +
    "William\n" +
    "Ethan\n" +
    "James\n" +
    "Alexander\n" +
    "Michael\n" +
    "Benjamin\n" +
    "Elijah\n" +
    "Daniel\n" +
    "Aiden\n" +
    "Logan\n" +
    "Matthew\n" +
    "Lucas\n" +
    "Jackson\n" +
    "David\n" +
    "Oliver\n" +
    "Jayden\n" +
    "Joseph\n" +
    "Gabriel\n" +
    "Samuel\n" +
    "Carter\n" +
    "Anthony\n" +
    "John\n" +
    "Dylan\n" +
    "Luke\n" +
    "Henry\n" +
    "Andrew\n" +
    "Isaac\n" +
    "Christopher\n" +
    "Joshua\n" +
    "Wyatt\n" +
    "Sebastian\n" +
    "Owen\n" +
    "Caleb\n" +
    "Nathan\n" +
    "Ryan\n" +
    "Jack\n" +
    "Hunter\n" +
    "Levi\n" +
    "Christian\n" +
    "Jaxon\n" +
    "Julian\n" +
    "Landon\n" +
    "Grayson\n" +
    "Jonathan\n" +
    "Isaiah\n" +
    "Charles\n" +
    "Thomas\n" +
    "Aaron\n" +
    "Eli\n" +
    "Connor\n" +
    "Jeremiah\n" +
    "Cameron\n" +
    "Josiah\n" +
    "Adrian\n" +
    "Colton\n" +
    "Jordan\n" +
    "Brayden\n" +
    "Nicholas\n" +
    "Robert\n" +
    "Angel\n" +
    "Hudson\n" +
    "Lincoln\n" +
    "Evan\n" +
    "Dominic\n" +
    "Austin\n" +
    "Gavin\n" +
    "Nolan\n" +
    "Parker\n" +
    "Adam\n" +
    "Chase\n" +
    "Jace\n" +
    "Ian\n" +
    "Cooper\n" +
    "Easton\n" +
    "Kevin\n" +
    "Jose\n" +
    "Tyler\n" +
    "Brandon\n" +
    "Asher\n" +
    "Jaxson\n" +
    "Mateo\n";
var male_names = male_list.split('\n');
console.log(male_names.slice(0, 10));
