"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.genders = ["Male", "Female"];
let male_list = "Noah\n" +
    "Liam\n" +
    "Mason\n" +
    "Jacob\n" +
    "William\n" +
    "Ethan\n" +
    "James\n" +
    "Alexander\n" +
    "Michael\n" +
    "Benjamin\n" +
    "Elijah\n" +
    "Daniel\n" +
    "Aiden\n" +
    "Logan\n" +
    "Matthew\n" +
    "Lucas\n" +
    "Jackson\n" +
    "David\n" +
    "Oliver\n" +
    "Jayden\n" +
    "Joseph\n" +
    "Gabriel\n" +
    "Samuel\n" +
    "Carter\n" +
    "Anthony\n" +
    "John\n" +
    "Dylan\n" +
    "Luke\n" +
    "Henry\n" +
    "Andrew\n" +
    "Isaac\n" +
    "Christopher\n" +
    "Joshua\n" +
    "Wyatt\n" +
    "Sebastian\n" +
    "Owen\n" +
    "Caleb\n" +
    "Nathan\n" +
    "Ryan\n" +
    "Jack\n" +
    "Hunter\n" +
    "Levi\n" +
    "Christian\n" +
    "Jaxon\n" +
    "Julian\n" +
    "Landon\n" +
    "Grayson\n" +
    "Jonathan\n" +
    "Isaiah\n" +
    "Charles\n" +
    "Thomas\n" +
    "Aaron\n" +
    "Eli\n" +
    "Connor\n" +
    "Jeremiah\n" +
    "Cameron\n" +
    "Josiah\n" +
    "Adrian\n" +
    "Colton\n" +
    "Jordan\n" +
    "Brayden\n" +
    "Nicholas\n" +
    "Robert\n" +
    "Angel\n" +
    "Hudson\n" +
    "Lincoln\n" +
    "Evan\n" +
    "Dominic\n" +
    "Austin\n" +
    "Gavin\n" +
    "Nolan\n" +
    "Parker\n" +
    "Adam\n" +
    "Chase\n" +
    "Jace\n" +
    "Ian\n" +
    "Cooper\n" +
    "Easton\n" +
    "Kevin\n" +
    "Jose\n" +
    "Tyler\n" +
    "Brandon\n" +
    "Asher\n" +
    "Jaxson\n" +
    "Mateo\n";
let female_list = "Emma\n" +
    "Olivia\n" +
    "Sophia\n" +
    "Ava\n" +
    "Isabella\n" +
    "Mia\n" +
    "Abigail\n" +
    "Emily\n" +
    "Charlotte\n" +
    "Harper\n" +
    "Madison\n" +
    "Amelia\n" +
    "Elizabeth\n" +
    "Sofia\n" +
    "Evelyn\n" +
    "Avery\n" +
    "Chloe\n" +
    "Ella\n" +
    "Grace\n" +
    "Victoria\n" +
    "Aubrey\n" +
    "Scarlett\n" +
    "Zoey\n" +
    "Addison\n" +
    "Lily\n" +
    "Lillian\n" +
    "Natalie\n" +
    "Hannah\n" +
    "Aria\n" +
    "Layla\n" +
    "Brooklyn\n" +
    "Alexa\n" +
    "Zoe\n" +
    "Penelope\n" +
    "Riley\n" +
    "Leah\n" +
    "Audrey\n" +
    "Savannah\n" +
    "Allison\n" +
    "Samantha\n" +
    "Nora\n" +
    "Skylar\n" +
    "Camila\n" +
    "Anna\n" +
    "Paisley\n" +
    "Ariana\n" +
    "Ellie\n" +
    "Aaliyah\n" +
    "Claire\n" +
    "Violet\n" +
    "Stella\n" +
    "Sadie\n" +
    "Mila\n" +
    "Gabriella\n" +
    "Lucy\n" +
    "Arianna\n" +
    "Kennedy\n" +
    "Sarah\n" +
    "Madelyn\n" +
    "Eleanor\n" +
    "Kaylee\n" +
    "Caroline\n" +
    "Hazel\n" +
    "Hailey\n" +
    "Genesis\n" +
    "Kylie\n" +
    "Autumn\n" +
    "Piper\n" +
    "Maya\n" +
    "Nevaeh\n" +
    "Serenity\n" +
    "Peyton\n" +
    "Mackenzie\n" +
    "Bella\n" +
    "Eva\n" +
    "Taylor\n" +
    "Naomi\n" +
    "Aubree\n" +
    "Aurora\n" +
    "Melanie\n" +
    "Lydia\n" +
    "Brianna\n" +
    "Ruby\n" +
    "Katherine\n" +
    "Ashley\n" +
    "Alexis\n" +
    "Alice\n" +
    "Cora\n" +
    "Julia\n" +
    "Madeline\n" +
    "Faith\n" +
    "Annabelle\n" +
    "Alyssa\n" +
    "Isabelle\n" +
    "Vivian\n" +
    "Gianna\n" +
    "Quinn\n" +
    "Clara\n" +
    "Reagan\n" +
    "Khloe\n" +
    "Alexandra\n" +
    "Hadley\n" +
    "Eliana\n" +
    "Sophie\n" +
    "London\n" +
    "Elena\n" +
    "Kimberly\n" +
    "Bailey\n" +
    "Maria\n" +
    "Luna\n" +
    "Willow\n" +
    "Jasmine\n" +
    "Kinsley\n" +
    "Valentina\n" +
    "Kayla\n" +
    "Delilah\n" +
    "Andrea\n" +
    "Natalia\n" +
    "Lauren\n" +
    "Morgan\n" +
    "Rylee\n" +
    "Sydney\n" +
    "Adalynn\n" +
    "Mary\n" +
    "Ximena\n" +
    "Jade\n" +
    "Liliana\n" +
    "Brielle\n" +
    "Ivy\n" +
    "Trinity\n" +
    "Josephine\n" +
    "Adalyn\n" +
    "Jocelyn\n" +
    "Emery\n" +
    "Adeline\n" +
    "Jordyn\n" +
    "Ariel\n" +
    "Everly\n" +
    "Lilly\n" +
    "Paige\n" +
    "Isla\n" +
    "Lyla\n" +
    "Makayla\n" +
    "Molly\n" +
    "Emilia\n" +
    "Mya\n" +
    "Kendall\n" +
    "Melody\n" +
    "Isabel\n" +
    "Brooke\n" +
    "Mckenzie\n" +
    "Nicole\n" +
    "Payton\n" +
    "Margaret\n" +
    "Mariah\n" +
    "Eden\n" +
    "Athena\n" +
    "Amy";
exports.female_names = female_list.split('\n');
exports.male_names = male_list.split('\n');
